name: ja_rating
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6  # Actualizado a la última versión
  
  # Imágenes
  image_picker: ^1.1.2
  
  # HTTP y utilidades
  http: ^1.1.0
  google_fonts: ^8.0.2
  flutter_dotenv: ^5.1.0

  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: HoshikoSatsuki
      fonts:
        - asset: lib/fonts/Hoshiko Satsuki.ttf
  
  assets:
    - assets/imagenes/logo.png
    - assets/imagenes/brush.png
    - assets/imagenes/mapa_antiguo.jpg
