name: ja_rating
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2

  google_fonts: ^8.0.2
  http: ^1.6.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # Aquí és on afegim les nostres fonts personalitzades
  fonts:
    - family: HoshikoSatsuki  # Aquest és el nom que utilitzaràs al codi
      fonts:
        - asset: lib/fonts/Hoshiko Satsuki.ttf
        # Si la font tingués més variants (negreta, cursiva...), les afegiries aquí
        # - asset: fonts/Hoshiko_Satsuki_Bold.ttf
        #   weight: 700
  assets:
    - assets/imagenes/logo.png
    - "assets/imagenes/papel rasgado.png"
    - assets/imagenes/puntos_comic.png
    - assets/imagenes/brush.png
